# Generated by Django 4.0 on 2022-05-14 19:21

from django.db import migrations

def load_new_emotions(apps, schema_editor):
  Score = apps.get_model('tracker', 'Score')

  scores = [
    Score(score =  5), # angry 😡
    Score(score =  6), # drunk  🥴
    Score(score =  7), # exited  😄
    Score(score =  8), # loving  🥰
    Score(score =  9), # funny 🤪
    Score(score = 10), # tired 😑
    Score(score = 11), # calm 😌
    Score(score = 12), # neutral 😐
    Score(score = 13), # fearful  😱
    Score(score = 14), # depressed 😣
    Score(score = 15), # cheerful 😊
    Score(score = 16), # worried 😟
    Score(score = 17), # tired 😴
  ]

  for score in scores: score.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_entry_context'),
    ]

    operations = [
      migrations.RunPython(load_new_emotions),
    ]

